// Generates src/generated/linkIndex.ts: compact per-family route metadata
// (slug + display name + the few numbers the linking engine needs).
//
// Why: the internal linking engine runs on every page via ContentPage. If it
// imported the full data files it would pull ~2MB of content data into every
// route's JS graph. This index is ~2% of that size. Run via vite-node (so TS
// data files import directly) at the start of every build.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { famousIQData } from "../src/data/famousIQData";
import { careerIQData } from "../src/data/careerIQData";
import { majorIQData } from "../src/data/majorIQData";
import { cityIQData } from "../src/data/cityIQData";
import { countryIQData } from "../src/data/countryIQData";
import { stateIQData } from "../src/data/stateIQData";
import { conditionIQData } from "../src/data/conditionIQData";
import { iqMythData } from "../src/data/iqMythData";
import { iqCompareData } from "../src/data/iqCompareData";
import { ageIQData } from "../src/data/ageIQData";
import { iqScores } from "../src/data/iqScoreData";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const index = {
  famous: famousIQData.map((p) => ({ slug: p.slug, name: p.name, iq: p.estimatedIQ, mid: p.estimatedIQMid, field: p.field })),
  careers: careerIQData.map((c) => ({ slug: c.slug, name: c.career, minIQ: c.minIQ, maxIQ: c.maxIQ })),
  majors: majorIQData.map((m) => ({ slug: m.slug, name: m.major })),
  cities: cityIQData.map((c) => ({ slug: c.slug, name: c.city })),
  countries: countryIQData.map((c) => ({ slug: c.slug, name: c.name })),
  states: stateIQData.map((s) => ({ slug: s.slug, name: s.name })),
  conditions: conditionIQData.map((c) => ({ slug: c.slug, name: c.name })),
  myths: iqMythData.map((m) => ({ slug: m.slug, name: m.title })),
  compares: iqCompareData.map((c) => ({ slug: c.slug, name: c.title })),
  ages: ageIQData.map((a) => ({ slug: a.slug, name: a.ageGroup })),
  scores: iqScores,
};

const out = `// AUTO-GENERATED by scripts/gen-link-index.mts. Do not edit by hand.
// Compact route metadata for the internal linking engine and route tables;
// keeps full content data files out of the shared JS graph.

export interface FamousIndexEntry { slug: string; name: string; iq: string; mid: number; field: string }
export interface NamedIndexEntry { slug: string; name: string }
export interface CareerIndexEntry { slug: string; name: string; minIQ: number; maxIQ: number }

export const famousIndex: FamousIndexEntry[] = ${JSON.stringify(index.famous)};
export const careerIndex: CareerIndexEntry[] = ${JSON.stringify(index.careers)};
export const majorIndex: NamedIndexEntry[] = ${JSON.stringify(index.majors)};
export const cityIndex: NamedIndexEntry[] = ${JSON.stringify(index.cities)};
export const countryIndex: NamedIndexEntry[] = ${JSON.stringify(index.countries)};
export const stateIndex: NamedIndexEntry[] = ${JSON.stringify(index.states)};
export const conditionIndex: NamedIndexEntry[] = ${JSON.stringify(index.conditions)};
export const mythIndex: NamedIndexEntry[] = ${JSON.stringify(index.myths)};
export const compareIndex: NamedIndexEntry[] = ${JSON.stringify(index.compares)};
export const ageIndex: NamedIndexEntry[] = ${JSON.stringify(index.ages)};
export const scoreIndex: number[] = ${JSON.stringify(index.scores)};
`;

fs.mkdirSync(path.resolve(__dirname, "../src/generated"), { recursive: true });
fs.writeFileSync(path.resolve(__dirname, "../src/generated/linkIndex.ts"), out);
console.log(
  `linkIndex.ts: famous=${index.famous.length} careers=${index.careers.length} countries=${index.countries.length} scores=${index.scores.length}`,
);
